// <auto-generated />
using BackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MGContext))]
    partial class MGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Duzina")
                        .HasColumnType("int")
                        .HasColumnName("Duzina");

                    b.Property<string>("Glumac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Glumac");

                    b.Property<int>("Godina")
                        .HasColumnType("int")
                        .HasColumnName("Godina");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<bool>("Oskar")
                        .HasColumnType("bit")
                        .HasColumnName("Oskar");

                    b.Property<string>("Reziser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reziser");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Zanr");

                    b.Property<string>("Zemlja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Zemlja");

                    b.HasKey("ID");

                    b.ToTable("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
